
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.620
distribution_type: module
version: 0.22
name: PITA
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
requires: 
  File::Remove: 0.22
  File::Spec: 0.80
  Storable: 0
  PITA::Scheme: 0.29
  Data::GUID: 0.04
  Params::Util: 0.10
  File::Path: 0
  HTTP::Daemon: 0
  PITA::XML: 0.29
  File::Copy: 0
  File::Find::Rule: 0
  URI: 0
  PITA::Image: 0.29
  Process: 0.16
  version: 0.50
  Carp: 0
  perl: 5.005
  Archive::Extract: 0.07
  File::Temp: 0
  File::Basename: 0
  LWP: 5.69
abstract: The Practical Image Testing Architecture
